/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibraryJava */

#ifndef _Included_LibraryJava
#define _Included_LibraryJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibraryJava
 * Method:    execute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LibraryJava_execute
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
